name: fuckin_ide
description: A comprehensive IDE for Brainfuck programming.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.6.0
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.3
  git: ^2.3.1
  path_provider: ^2.1.5
  process_run: ^1.2.4
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  xterm: ^4.0.0
  yaml: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/ttf/JetBrainsMono-Regular.ttf