name: fuckin_ide
description: A comprehensive IDE for Brainfuck programming.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.12.5+2
  path_provider: ^2.1.1
  file_picker: ^5.5.0
  git: ^2.2.1
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  desktop_drop: ^0.4.4
  yaml: ^3.1.2
  xterm: ^4.0.0
  cupertino_icons: ^1.0.8
  flutter_code_editor: ^0.3.3
  flutter_bloc: ^8.1.3
  animate_do: ^4.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tcc/tcc_macos
    - assets/tcc/lib/include/stddef.h
    - assets/tcc/lib/include/stdarg.h
    - assets/tcc/lib/include/stdio.h

  # plugin:
  #   platforms:
  #     macos:
  #       pluginClass: FilePickerPlugin
